name: mel_consultoria
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/clientes_icon.png
    - assets/contato_icon.png
    - assets/empresa_icon.png
    - assets/servico_icon.png
    - assets/mel_consul.png
    - assets/ico2.png